/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.Agent = factory(root.ScubawhereApiDocumentation.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Agent model module.
   * @module model/Agent
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Agent</code>.
   * @alias module:model/Agent
   * @class
   */
  var exports = function() {
    var _this = this;













  };

  /**
   * Constructs a <code>Agent</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Agent} obj Optional instance to populate.
   * @return {module:model/Agent} The populated <code>Agent</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('website')) {
        obj['website'] = ApiClient.convertToType(data['website'], 'String');
      }
      if (data.hasOwnProperty('branch_name')) {
        obj['branch_name'] = ApiClient.convertToType(data['branch_name'], 'String');
      }
      if (data.hasOwnProperty('branch_address')) {
        obj['branch_address'] = ApiClient.convertToType(data['branch_address'], 'String');
      }
      if (data.hasOwnProperty('branch_phone')) {
        obj['branch_phone'] = ApiClient.convertToType(data['branch_phone'], 'String');
      }
      if (data.hasOwnProperty('branch_email')) {
        obj['branch_email'] = ApiClient.convertToType(data['branch_email'], 'String');
      }
      if (data.hasOwnProperty('billing_address')) {
        obj['billing_address'] = ApiClient.convertToType(data['billing_address'], 'String');
      }
      if (data.hasOwnProperty('billing_phone')) {
        obj['billing_phone'] = ApiClient.convertToType(data['billing_phone'], 'String');
      }
      if (data.hasOwnProperty('billing_email')) {
        obj['billing_email'] = ApiClient.convertToType(data['billing_email'], 'String');
      }
      if (data.hasOwnProperty('commission')) {
        obj['commission'] = ApiClient.convertToType(data['commission'], 'Number');
      }
      if (data.hasOwnProperty('terms')) {
        obj['terms'] = ApiClient.convertToType(data['terms'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} website
   */
  exports.prototype['website'] = undefined;
  /**
   * @member {String} branch_name
   */
  exports.prototype['branch_name'] = undefined;
  /**
   * @member {String} branch_address
   */
  exports.prototype['branch_address'] = undefined;
  /**
   * @member {String} branch_phone
   */
  exports.prototype['branch_phone'] = undefined;
  /**
   * @member {String} branch_email
   */
  exports.prototype['branch_email'] = undefined;
  /**
   * @member {String} billing_address
   */
  exports.prototype['billing_address'] = undefined;
  /**
   * @member {String} billing_phone
   */
  exports.prototype['billing_phone'] = undefined;
  /**
   * @member {String} billing_email
   */
  exports.prototype['billing_email'] = undefined;
  /**
   * @member {Number} commission
   */
  exports.prototype['commission'] = undefined;
  /**
   * @member {String} terms
   */
  exports.prototype['terms'] = undefined;



  return exports;
}));


