/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Addon'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Addon'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.InlineResponse20010 = factory(root.ScubawhereApiDocumentation.ApiClient, root.ScubawhereApiDocumentation.Addon);
  }
}(this, function(ApiClient, Addon) {
  'use strict';




  /**
   * The InlineResponse20010 model module.
   * @module model/InlineResponse20010
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InlineResponse20010</code>.
   * @alias module:model/InlineResponse20010
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>InlineResponse20010</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20010} obj Optional instance to populate.
   * @return {module:model/InlineResponse20010} The populated <code>InlineResponse20010</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('addons')) {
        obj['addons'] = ApiClient.convertToType(data['addons'], [Addon]);
      }
      if (data.hasOwnProperty('decimal_price')) {
        obj['decimal_price'] = ApiClient.convertToType(data['decimal_price'], 'String');
      }
      if (data.hasOwnProperty('boatroom_id')) {
        obj['boatroom_id'] = ApiClient.convertToType(data['boatroom_id'], 'Integer');
      }
      if (data.hasOwnProperty('package_decimal_price')) {
        obj['package_decimal_price'] = ApiClient.convertToType(data['package_decimal_price'], 'String');
      }
      if (data.hasOwnProperty('course_decimal_price')) {
        obj['course_decimal_price'] = ApiClient.convertToType(data['course_decimal_price'], 'String');
      }
      if (data.hasOwnProperty('ticket_decimal_price')) {
        obj['ticket_decimal_price'] = ApiClient.convertToType(data['ticket_decimal_price'], 'String');
      }
      if (data.hasOwnProperty('packagefacade_id')) {
        obj['packagefacade_id'] = ApiClient.convertToType(data['packagefacade_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Array.<module:model/Addon>} addons
   */
  exports.prototype['addons'] = undefined;
  /**
   * @member {String} decimal_price
   */
  exports.prototype['decimal_price'] = undefined;
  /**
   * @member {Integer} boatroom_id
   */
  exports.prototype['boatroom_id'] = undefined;
  /**
   * @member {String} package_decimal_price
   */
  exports.prototype['package_decimal_price'] = undefined;
  /**
   * @member {String} course_decimal_price
   */
  exports.prototype['course_decimal_price'] = undefined;
  /**
   * @member {String} ticket_decimal_price
   */
  exports.prototype['ticket_decimal_price'] = undefined;
  /**
   * @member {String} packagefacade_id
   */
  exports.prototype['packagefacade_id'] = undefined;



  return exports;
}));


