/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DateRange', 'model/ReportEntry', 'model/ReportEntryTotal'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DateRange'), require('./ReportEntry'), require('./ReportEntryTotal'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.InlineResponse20040 = factory(root.ScubawhereApiDocumentation.ApiClient, root.ScubawhereApiDocumentation.DateRange, root.ScubawhereApiDocumentation.ReportEntry, root.ScubawhereApiDocumentation.ReportEntryTotal);
  }
}(this, function(ApiClient, DateRange, ReportEntry, ReportEntryTotal) {
  'use strict';




  /**
   * The InlineResponse20040 model module.
   * @module model/InlineResponse20040
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InlineResponse20040</code>.
   * @alias module:model/InlineResponse20040
   * @class
   */
  var exports = function() {
    var _this = this;














  };

  /**
   * Constructs a <code>InlineResponse20040</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20040} obj Optional instance to populate.
   * @return {module:model/InlineResponse20040} The populated <code>InlineResponse20040</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('daterange')) {
        obj['daterange'] = DateRange.constructFromObject(data['daterange']);
      }
      if (data.hasOwnProperty('accommodations')) {
        obj['accommodations'] = ReportEntry.constructFromObject(data['accommodations']);
      }
      if (data.hasOwnProperty('accommodation_toal')) {
        obj['accommodation_toal'] = ReportEntryTotal.constructFromObject(data['accommodation_toal']);
      }
      if (data.hasOwnProperty('addons')) {
        obj['addons'] = ReportEntry.constructFromObject(data['addons']);
      }
      if (data.hasOwnProperty('addons_toal')) {
        obj['addons_toal'] = ReportEntryTotal.constructFromObject(data['addons_toal']);
      }
      if (data.hasOwnProperty('courses')) {
        obj['courses'] = ReportEntry.constructFromObject(data['courses']);
      }
      if (data.hasOwnProperty('courses_toal')) {
        obj['courses_toal'] = ReportEntryTotal.constructFromObject(data['courses_toal']);
      }
      if (data.hasOwnProperty('fees')) {
        obj['fees'] = ReportEntry.constructFromObject(data['fees']);
      }
      if (data.hasOwnProperty('fees_toal')) {
        obj['fees_toal'] = ReportEntryTotal.constructFromObject(data['fees_toal']);
      }
      if (data.hasOwnProperty('packages')) {
        obj['packages'] = ReportEntry.constructFromObject(data['packages']);
      }
      if (data.hasOwnProperty('package_toal')) {
        obj['package_toal'] = ReportEntryTotal.constructFromObject(data['package_toal']);
      }
      if (data.hasOwnProperty('tickets')) {
        obj['tickets'] = ReportEntry.constructFromObject(data['tickets']);
      }
      if (data.hasOwnProperty('ticket_toal')) {
        obj['ticket_toal'] = ReportEntryTotal.constructFromObject(data['ticket_toal']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DateRange} daterange
   */
  exports.prototype['daterange'] = undefined;
  /**
   * @member {module:model/ReportEntry} accommodations
   */
  exports.prototype['accommodations'] = undefined;
  /**
   * @member {module:model/ReportEntryTotal} accommodation_toal
   */
  exports.prototype['accommodation_toal'] = undefined;
  /**
   * @member {module:model/ReportEntry} addons
   */
  exports.prototype['addons'] = undefined;
  /**
   * @member {module:model/ReportEntryTotal} addons_toal
   */
  exports.prototype['addons_toal'] = undefined;
  /**
   * @member {module:model/ReportEntry} courses
   */
  exports.prototype['courses'] = undefined;
  /**
   * @member {module:model/ReportEntryTotal} courses_toal
   */
  exports.prototype['courses_toal'] = undefined;
  /**
   * @member {module:model/ReportEntry} fees
   */
  exports.prototype['fees'] = undefined;
  /**
   * @member {module:model/ReportEntryTotal} fees_toal
   */
  exports.prototype['fees_toal'] = undefined;
  /**
   * @member {module:model/ReportEntry} packages
   */
  exports.prototype['packages'] = undefined;
  /**
   * @member {module:model/ReportEntryTotal} package_toal
   */
  exports.prototype['package_toal'] = undefined;
  /**
   * @member {module:model/ReportEntry} tickets
   */
  exports.prototype['tickets'] = undefined;
  /**
   * @member {module:model/ReportEntryTotal} ticket_toal
   */
  exports.prototype['ticket_toal'] = undefined;



  return exports;
}));


