/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/DateRange'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./DateRange'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.InlineResponse20041 = factory(root.ScubawhereApiDocumentation.ApiClient, root.ScubawhereApiDocumentation.DateRange);
  }
}(this, function(ApiClient, DateRange) {
  'use strict';




  /**
   * The InlineResponse20041 model module.
   * @module model/InlineResponse20041
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>InlineResponse20041</code>.
   * @alias module:model/InlineResponse20041
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>InlineResponse20041</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/InlineResponse20041} obj Optional instance to populate.
   * @return {module:model/InlineResponse20041} The populated <code>InlineResponse20041</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('daterange')) {
        obj['daterange'] = DateRange.constructFromObject(data['daterange']);
      }
      if (data.hasOwnProperty('source_frequency')) {
        obj['source_frequency'] = ApiClient.convertToType(data['source_frequency'], ['Integer']);
      }
      if (data.hasOwnProperty('source_revenue')) {
        obj['source_revenue'] = ApiClient.convertToType(data['source_revenue'], ['Integer']);
      }
    }
    return obj;
  }

  /**
   * @member {module:model/DateRange} daterange
   */
  exports.prototype['daterange'] = undefined;
  /**
   * @member {Array.<Integer>} source_frequency
   */
  exports.prototype['source_frequency'] = undefined;
  /**
   * @member {Array.<Integer>} source_revenue
   */
  exports.prototype['source_revenue'] = undefined;



  return exports;
}));


