/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Trip'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Trip'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.Ticket = factory(root.ScubawhereApiDocumentation.ApiClient, root.ScubawhereApiDocumentation.Trip);
  }
}(this, function(ApiClient, Trip) {
  'use strict';




  /**
   * The Ticket model module.
   * @module model/Ticket
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Ticket</code>.
   * @alias module:model/Ticket
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>Ticket</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Ticket} obj Optional instance to populate.
   * @return {module:model/Ticket} The populated <code>Ticket</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('name')) {
        obj['name'] = ApiClient.convertToType(data['name'], 'String');
      }
      if (data.hasOwnProperty('description')) {
        obj['description'] = ApiClient.convertToType(data['description'], 'String');
      }
      if (data.hasOwnProperty('only_packaged')) {
        obj['only_packaged'] = ApiClient.convertToType(data['only_packaged'], 'Boolean');
      }
      if (data.hasOwnProperty('available_from')) {
        obj['available_from'] = ApiClient.convertToType(data['available_from'], 'Date');
      }
      if (data.hasOwnProperty('available_until')) {
        obj['available_until'] = ApiClient.convertToType(data['available_until'], 'Date');
      }
      if (data.hasOwnProperty('trips')) {
        obj['trips'] = ApiClient.convertToType(data['trips'], [Trip]);
      }
    }
    return obj;
  }

  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {String} name
   */
  exports.prototype['name'] = undefined;
  /**
   * @member {String} description
   */
  exports.prototype['description'] = undefined;
  /**
   * @member {Boolean} only_packaged
   */
  exports.prototype['only_packaged'] = undefined;
  /**
   * @member {Date} available_from
   */
  exports.prototype['available_from'] = undefined;
  /**
   * @member {Date} available_until
   */
  exports.prototype['available_until'] = undefined;
  /**
   * @member {Array.<module:model/Trip>} trips
   */
  exports.prototype['trips'] = undefined;



  return exports;
}));


