/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Customer', 'model/TrainingSessionManifestCapacity'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Customer'), require('./TrainingSessionManifestCapacity'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.TrainingSessionManifest = factory(root.ScubawhereApiDocumentation.ApiClient, root.ScubawhereApiDocumentation.Customer, root.ScubawhereApiDocumentation.TrainingSessionManifestCapacity);
  }
}(this, function(ApiClient, Customer, TrainingSessionManifestCapacity) {
  'use strict';




  /**
   * The TrainingSessionManifest model module.
   * @module model/TrainingSessionManifest
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>TrainingSessionManifest</code>.
   * @alias module:model/TrainingSessionManifest
   * @class
   */
  var exports = function() {
    var _this = this;







  };

  /**
   * Constructs a <code>TrainingSessionManifest</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/TrainingSessionManifest} obj Optional instance to populate.
   * @return {module:model/TrainingSessionManifest} The populated <code>TrainingSessionManifest</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('id')) {
        obj['id'] = ApiClient.convertToType(data['id'], 'Integer');
      }
      if (data.hasOwnProperty('training_id')) {
        obj['training_id'] = ApiClient.convertToType(data['training_id'], 'Integer');
      }
      if (data.hasOwnProperty('start')) {
        obj['start'] = ApiClient.convertToType(data['start'], 'Date');
      }
      if (data.hasOwnProperty('schedule_id')) {
        obj['schedule_id'] = ApiClient.convertToType(data['schedule_id'], 'Integer');
      }
      if (data.hasOwnProperty('customers')) {
        obj['customers'] = ApiClient.convertToType(data['customers'], [Customer]);
      }
      if (data.hasOwnProperty('capacity')) {
        obj['capacity'] = TrainingSessionManifestCapacity.constructFromObject(data['capacity']);
      }
    }
    return obj;
  }

  /**
   * @member {Integer} id
   */
  exports.prototype['id'] = undefined;
  /**
   * @member {Integer} training_id
   */
  exports.prototype['training_id'] = undefined;
  /**
   * @member {Date} start
   */
  exports.prototype['start'] = undefined;
  /**
   * @member {Integer} schedule_id
   */
  exports.prototype['schedule_id'] = undefined;
  /**
   * @member {Array.<module:model/Customer>} customers
   */
  exports.prototype['customers'] = undefined;
  /**
   * @member {module:model/TrainingSessionManifestCapacity} capacity
   */
  exports.prototype['capacity'] = undefined;



  return exports;
}));


