/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorModel', 'model/InlineResponse2004', 'model/InlineResponse2003', 'model/Agent'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorModel'), require('../model/InlineResponse2004'), require('../model/InlineResponse2003'), require('../model/Agent'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.AgentApi = factory(root.ScubawhereApiDocumentation.ApiClient, root.ScubawhereApiDocumentation.ErrorModel, root.ScubawhereApiDocumentation.InlineResponse2004, root.ScubawhereApiDocumentation.InlineResponse2003, root.ScubawhereApiDocumentation.Agent);
  }
}(this, function(ApiClient, ErrorModel, InlineResponse2004, InlineResponse2003, Agent) {
  'use strict';

  /**
   * Agent service.
   * @module api/AgentApi
   * @version 1.0.0
   */

  /**
   * Constructs a new AgentApi. 
   * @alias module:api/AgentApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createAgent operation.
     * @callback module:api/AgentApi~createAgentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2004} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new agent
     * @param {Integer} name 
     * @param {String} branchName 
     * @param {String} branchAddress 
     * @param {String} branchPhone 
     * @param {String} branchEmail 
     * @param {Number} commission 
     * @param {String} terms 
     * @param {Object} opts Optional parameters
     * @param {String} opts.website 
     * @param {String} opts.billingAddress 
     * @param {String} opts.billingPhone 
     * @param {String} opts.billingEmail 
     * @param {module:api/AgentApi~createAgentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2004}
     */
    this.createAgent = function(name, branchName, branchAddress, branchPhone, branchEmail, commission, terms, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'name' is set
      if (name == undefined || name == null) {
        throw "Missing the required parameter 'name' when calling createAgent";
      }

      // verify the required parameter 'branchName' is set
      if (branchName == undefined || branchName == null) {
        throw "Missing the required parameter 'branchName' when calling createAgent";
      }

      // verify the required parameter 'branchAddress' is set
      if (branchAddress == undefined || branchAddress == null) {
        throw "Missing the required parameter 'branchAddress' when calling createAgent";
      }

      // verify the required parameter 'branchPhone' is set
      if (branchPhone == undefined || branchPhone == null) {
        throw "Missing the required parameter 'branchPhone' when calling createAgent";
      }

      // verify the required parameter 'branchEmail' is set
      if (branchEmail == undefined || branchEmail == null) {
        throw "Missing the required parameter 'branchEmail' when calling createAgent";
      }

      // verify the required parameter 'commission' is set
      if (commission == undefined || commission == null) {
        throw "Missing the required parameter 'commission' when calling createAgent";
      }

      // verify the required parameter 'terms' is set
      if (terms == undefined || terms == null) {
        throw "Missing the required parameter 'terms' when calling createAgent";
      }


      var pathParams = {
      };
      var queryParams = {
        'name': name,
        'website': opts['website'],
        'branch_name': branchName,
        'branch_address': branchAddress,
        'branch_phone': branchPhone,
        'branch_email': branchEmail,
        'billing_address': opts['billingAddress'],
        'billing_phone': opts['billingPhone'],
        'billing_email': opts['billingEmail'],
        'commission': commission,
        'terms': terms
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2004;

      return this.apiClient.callApi(
        '/agent/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteAgent operation.
     * @callback module:api/AgentApi~deleteAgentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete an agent by ID
     * @param {Integer} id ID of the Agent
     * @param {module:api/AgentApi~deleteAgentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    this.deleteAgent = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling deleteAgent";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/agent/delete', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAgent operation.
     * @callback module:api/AgentApi~getAgentCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2004} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve an agent by ID
     * @param {Integer} id ID of the agent to be retrieved
     * @param {module:api/AgentApi~getAgentCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2004}
     */
    this.getAgent = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getAgent";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2004;

      return this.apiClient.callApi(
        '/agent', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllAgents operation.
     * @callback module:api/AgentApi~getAllAgentsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Agent>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all agents
     * @param {module:api/AgentApi~getAllAgentsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Agent>}
     */
    this.getAllAgents = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Agent];

      return this.apiClient.callApi(
        '/agent/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllWithTrashedAgents operation.
     * @callback module:api/AgentApi~getAllWithTrashedAgentsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Agent>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all agents including any deleted models
     * @param {module:api/AgentApi~getAllWithTrashedAgentsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Agent>}
     */
    this.getAllWithTrashedAgents = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Agent];

      return this.apiClient.callApi(
        '/agent/all-with-trashed', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
