/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Training', 'model/ErrorModel', 'model/InlineResponse20021', 'model/InlineResponse2003', 'model/InlineResponse20022'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Training'), require('../model/ErrorModel'), require('../model/InlineResponse20021'), require('../model/InlineResponse2003'), require('../model/InlineResponse20022'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.ClassApi = factory(root.ScubawhereApiDocumentation.ApiClient, root.ScubawhereApiDocumentation.Training, root.ScubawhereApiDocumentation.ErrorModel, root.ScubawhereApiDocumentation.InlineResponse20021, root.ScubawhereApiDocumentation.InlineResponse2003, root.ScubawhereApiDocumentation.InlineResponse20022);
  }
}(this, function(ApiClient, Training, ErrorModel, InlineResponse20021, InlineResponse2003, InlineResponse20022) {
  'use strict';

  /**
   * Class service.
   * @module api/ClassApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ClassApi. 
   * @alias module:api/ClassApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the classGet operation.
     * @callback module:api/ClassApi~classGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Training} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a class by ID
     * @param {Integer} id 
     * @param {module:api/ClassApi~classGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Training}
     */
    this.classGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling classGet";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Training;

      return this.apiClient.callApi(
        '/class', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the createClass operation.
     * @callback module:api/ClassApi~createClassCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20021} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new class
     * @param {String} name 
     * @param {Number} duration 
     * @param {Object} opts Optional parameters
     * @param {String} opts.description 
     * @param {module:api/ClassApi~createClassCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20021}
     */
    this.createClass = function(name, duration, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'name' is set
      if (name == undefined || name == null) {
        throw "Missing the required parameter 'name' when calling createClass";
      }

      // verify the required parameter 'duration' is set
      if (duration == undefined || duration == null) {
        throw "Missing the required parameter 'duration' when calling createClass";
      }


      var pathParams = {
      };
      var queryParams = {
        'name': name,
        'description': opts['description'],
        'duration': duration
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20021;

      return this.apiClient.callApi(
        '/class/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteClass operation.
     * @callback module:api/ClassApi~deleteClassCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a class by ID
     * @param {Integer} id 
     * @param {module:api/ClassApi~deleteClassCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    this.deleteClass = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling deleteClass";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/class/delete', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the editClass operation.
     * @callback module:api/ClassApi~editClassCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20022} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a class by ID
     * @param {Integer} id 
     * @param {String} name 
     * @param {Number} duration 
     * @param {Object} opts Optional parameters
     * @param {String} opts.description 
     * @param {module:api/ClassApi~editClassCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20022}
     */
    this.editClass = function(id, name, duration, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling editClass";
      }

      // verify the required parameter 'name' is set
      if (name == undefined || name == null) {
        throw "Missing the required parameter 'name' when calling editClass";
      }

      // verify the required parameter 'duration' is set
      if (duration == undefined || duration == null) {
        throw "Missing the required parameter 'duration' when calling editClass";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id,
        'name': name,
        'description': opts['description'],
        'duration': duration
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20022;

      return this.apiClient.callApi(
        '/class/edit', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllClass operation.
     * @callback module:api/ClassApi~getAllClassCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Training>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all classes including any deleted models
     * @param {module:api/ClassApi~getAllClassCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Training>}
     */
    this.getAllClass = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Training];

      return this.apiClient.callApi(
        '/class/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllWithTrashedClass operation.
     * @callback module:api/ClassApi~getAllWithTrashedClassCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Training>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all classes including any deleted models
     * @param {module:api/ClassApi~getAllWithTrashedClassCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Training>}
     */
    this.getAllWithTrashedClass = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Training];

      return this.apiClient.callApi(
        '/class/all-with-trashed', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
