/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorModel', 'model/InlineResponse2015', 'model/Timetable'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorModel'), require('../model/InlineResponse2015'), require('../model/Timetable'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.TimetableApi = factory(root.ScubawhereApiDocumentation.ApiClient, root.ScubawhereApiDocumentation.ErrorModel, root.ScubawhereApiDocumentation.InlineResponse2015, root.ScubawhereApiDocumentation.Timetable);
  }
}(this, function(ApiClient, ErrorModel, InlineResponse2015, Timetable) {
  'use strict';

  /**
   * Timetable service.
   * @module api/TimetableApi
   * @version 1.0.0
   */

  /**
   * Constructs a new TimetableApi. 
   * @alias module:api/TimetableApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the addTimetable operation.
     * @callback module:api/TimetableApi~addTimetableCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2015} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new timetable for sessions
     * @param {String} schedule 
     * @param {Integer} sessionId 
     * @param {Object} opts Optional parameters
     * @param {Date} opts.until 
     * @param {module:api/TimetableApi~addTimetableCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2015}
     */
    this.addTimetable = function(schedule, sessionId, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'schedule' is set
      if (schedule == undefined || schedule == null) {
        throw "Missing the required parameter 'schedule' when calling addTimetable";
      }

      // verify the required parameter 'sessionId' is set
      if (sessionId == undefined || sessionId == null) {
        throw "Missing the required parameter 'sessionId' when calling addTimetable";
      }


      var pathParams = {
      };
      var queryParams = {
        'schedule': schedule,
        'session_id': sessionId,
        'until': opts['until']
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2015;

      return this.apiClient.callApi(
        '/timetable/add', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllTimetables operation.
     * @callback module:api/TimetableApi~getAllTimetablesCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Timetable>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all of the timetables for sessions
     * @param {module:api/TimetableApi~getAllTimetablesCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Timetable>}
     */
    this.getAllTimetables = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Timetable];

      return this.apiClient.callApi(
        '/timetable/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getTimetable operation.
     * @callback module:api/TimetableApi~getTimetableCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Timetable} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a timetable by ID
     * @param {Integer} id 
     * @param {module:api/TimetableApi~getTimetableCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Timetable}
     */
    this.getTimetable = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling getTimetable";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Timetable;

      return this.apiClient.callApi(
        '/timetable', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
