/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/ErrorModel', 'model/InlineResponse20046', 'model/InlineResponse2003', 'model/InlineResponse20047', 'model/Trip'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/ErrorModel'), require('../model/InlineResponse20046'), require('../model/InlineResponse2003'), require('../model/InlineResponse20047'), require('../model/Trip'));
  } else {
    // Browser globals (root is window)
    if (!root.ScubawhereApiDocumentation) {
      root.ScubawhereApiDocumentation = {};
    }
    root.ScubawhereApiDocumentation.TripApi = factory(root.ScubawhereApiDocumentation.ApiClient, root.ScubawhereApiDocumentation.ErrorModel, root.ScubawhereApiDocumentation.InlineResponse20046, root.ScubawhereApiDocumentation.InlineResponse2003, root.ScubawhereApiDocumentation.InlineResponse20047, root.ScubawhereApiDocumentation.Trip);
  }
}(this, function(ApiClient, ErrorModel, InlineResponse20046, InlineResponse2003, InlineResponse20047, Trip) {
  'use strict';

  /**
   * Trip service.
   * @module api/TripApi
   * @version 1.0.0
   */

  /**
   * Constructs a new TripApi. 
   * @alias module:api/TripApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the createTrip operation.
     * @callback module:api/TripApi~createTripCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20046} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new trip
     * @param {String} name 
     * @param {Number} duration 
     * @param {Array.<Integer>} locations 
     * @param {Array.<Integer>} tags 
     * @param {Object} opts Optional parameters
     * @param {String} opts.description 
     * @param {Boolean} opts.boatRequired 
     * @param {module:api/TripApi~createTripCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20046}
     */
    this.createTrip = function(name, duration, locations, tags, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'name' is set
      if (name == undefined || name == null) {
        throw "Missing the required parameter 'name' when calling createTrip";
      }

      // verify the required parameter 'duration' is set
      if (duration == undefined || duration == null) {
        throw "Missing the required parameter 'duration' when calling createTrip";
      }

      // verify the required parameter 'locations' is set
      if (locations == undefined || locations == null) {
        throw "Missing the required parameter 'locations' when calling createTrip";
      }

      // verify the required parameter 'tags' is set
      if (tags == undefined || tags == null) {
        throw "Missing the required parameter 'tags' when calling createTrip";
      }


      var pathParams = {
      };
      var queryParams = {
        'name': name,
        'description': opts['description'],
        'duration': duration,
        'boat_required': opts['boatRequired'],
        'locations': this.apiClient.buildCollectionParam(locations, 'multi'),
        'tags': this.apiClient.buildCollectionParam(tags, 'multi')
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20046;

      return this.apiClient.callApi(
        '/trip/add', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the deleteTrip operation.
     * @callback module:api/TripApi~deleteTripCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2003} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a trip by ID
     * @param {Integer} id 
     * @param {module:api/TripApi~deleteTripCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2003}
     */
    this.deleteTrip = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling deleteTrip";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse2003;

      return this.apiClient.callApi(
        '/trip/delete', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the editTrip operation.
     * @callback module:api/TripApi~editTripCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse20047} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update a trip by ID
     * @param {Integer} id 
     * @param {String} name 
     * @param {Number} duration 
     * @param {Array.<Integer>} locations 
     * @param {Array.<Integer>} tags 
     * @param {Object} opts Optional parameters
     * @param {String} opts.description 
     * @param {Boolean} opts.boatRequired 
     * @param {module:api/TripApi~editTripCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse20047}
     */
    this.editTrip = function(id, name, duration, locations, tags, opts, callback) {
      opts = opts || {};
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling editTrip";
      }

      // verify the required parameter 'name' is set
      if (name == undefined || name == null) {
        throw "Missing the required parameter 'name' when calling editTrip";
      }

      // verify the required parameter 'duration' is set
      if (duration == undefined || duration == null) {
        throw "Missing the required parameter 'duration' when calling editTrip";
      }

      // verify the required parameter 'locations' is set
      if (locations == undefined || locations == null) {
        throw "Missing the required parameter 'locations' when calling editTrip";
      }

      // verify the required parameter 'tags' is set
      if (tags == undefined || tags == null) {
        throw "Missing the required parameter 'tags' when calling editTrip";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id,
        'name': name,
        'description': opts['description'],
        'duration': duration,
        'boat_required': opts['boatRequired'],
        'locations': this.apiClient.buildCollectionParam(locations, 'multi'),
        'tags': this.apiClient.buildCollectionParam(tags, 'multi')
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = InlineResponse20047;

      return this.apiClient.callApi(
        '/trip/edit', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllTrips operation.
     * @callback module:api/TripApi~getAllTripsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Trip>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all trips including any deleted models
     * @param {module:api/TripApi~getAllTripsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Trip>}
     */
    this.getAllTrips = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Trip];

      return this.apiClient.callApi(
        '/trip/all', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getAllWithTrashedTrips operation.
     * @callback module:api/TripApi~getAllWithTrashedTripsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Trip>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve all trips including any deleted models
     * @param {module:api/TripApi~getAllWithTrashedTripsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Trip>}
     */
    this.getAllWithTrashedTrips = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Trip];

      return this.apiClient.callApi(
        '/trip/all-with-trashed', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the tripGet operation.
     * @callback module:api/TripApi~tripGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/Trip} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Retrieve a trip by ID
     * @param {Integer} id 
     * @param {module:api/TripApi~tripGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/Trip}
     */
    this.tripGet = function(id, callback) {
      var postBody = null;

      // verify the required parameter 'id' is set
      if (id == undefined || id == null) {
        throw "Missing the required parameter 'id' when calling tripGet";
      }


      var pathParams = {
      };
      var queryParams = {
        'id': id
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = Trip;

      return this.apiClient.callApi(
        '/trip', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
