/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ScubawhereApiDocumentation);
  }
}(this, function(expect, ScubawhereApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ScubawhereApiDocumentation.Customer();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Customer', function() {
    it('should create an instance of Customer', function() {
      // uncomment below and update the code to test Customer
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be.a(ScubawhereApiDocumentation.Customer);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property firstname (base name: "firstname")', function() {
      // uncomment below and update the code to test the property firstname
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property lastname (base name: "lastname")', function() {
      // uncomment below and update the code to test the property lastname
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property verified (base name: "verified")', function() {
      // uncomment below and update the code to test the property verified
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property birthday (base name: "birthday")', function() {
      // uncomment below and update the code to test the property birthday
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property address1 (base name: "address_1")', function() {
      // uncomment below and update the code to test the property address1
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property address2 (base name: "address_2")', function() {
      // uncomment below and update the code to test the property address2
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property city (base name: "city")', function() {
      // uncomment below and update the code to test the property city
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property county (base name: "county")', function() {
      // uncomment below and update the code to test the property county
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property postcode (base name: "postcode")', function() {
      // uncomment below and update the code to test the property postcode
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property countryId (base name: "country_id")', function() {
      // uncomment below and update the code to test the property countryId
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property phone (base name: "phone")', function() {
      // uncomment below and update the code to test the property phone
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property lastDive (base name: "last_dive")', function() {
      // uncomment below and update the code to test the property lastDive
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property numberOfDives (base name: "number_of_dives")', function() {
      // uncomment below and update the code to test the property numberOfDives
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property chestSize (base name: "chest_size")', function() {
      // uncomment below and update the code to test the property chestSize
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property shoeSize (base name: "shoe_size")', function() {
      // uncomment below and update the code to test the property shoeSize
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property cylinderSize (base name: "cylinder_size")', function() {
      // uncomment below and update the code to test the property cylinderSize
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property notes (base name: "notes")', function() {
      // uncomment below and update the code to test the property notes
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property unsubscribed (base name: "unsubscribed")', function() {
      // uncomment below and update the code to test the property unsubscribed
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

    it('should have the property country (base name: "country")', function() {
      // uncomment below and update the code to test the property country
      //var instane = new ScubawhereApiDocumentation.Customer();
      //expect(instance).to.be();
    });

  });

}));
