/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ScubawhereApiDocumentation);
  }
}(this, function(expect, ScubawhereApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ScubawhereApiDocumentation.InlineResponse20040();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('InlineResponse20040', function() {
    it('should create an instance of InlineResponse20040', function() {
      // uncomment below and update the code to test InlineResponse20040
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be.a(ScubawhereApiDocumentation.InlineResponse20040);
    });

    it('should have the property daterange (base name: "daterange")', function() {
      // uncomment below and update the code to test the property daterange
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property accommodations (base name: "accommodations")', function() {
      // uncomment below and update the code to test the property accommodations
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property accommodationToal (base name: "accommodation_toal")', function() {
      // uncomment below and update the code to test the property accommodationToal
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property addons (base name: "addons")', function() {
      // uncomment below and update the code to test the property addons
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property addonsToal (base name: "addons_toal")', function() {
      // uncomment below and update the code to test the property addonsToal
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property courses (base name: "courses")', function() {
      // uncomment below and update the code to test the property courses
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property coursesToal (base name: "courses_toal")', function() {
      // uncomment below and update the code to test the property coursesToal
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property fees (base name: "fees")', function() {
      // uncomment below and update the code to test the property fees
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property feesToal (base name: "fees_toal")', function() {
      // uncomment below and update the code to test the property feesToal
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property packages (base name: "packages")', function() {
      // uncomment below and update the code to test the property packages
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property packageToal (base name: "package_toal")', function() {
      // uncomment below and update the code to test the property packageToal
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property tickets (base name: "tickets")', function() {
      // uncomment below and update the code to test the property tickets
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

    it('should have the property ticketToal (base name: "ticket_toal")', function() {
      // uncomment below and update the code to test the property ticketToal
      //var instane = new ScubawhereApiDocumentation.InlineResponse20040();
      //expect(instance).to.be();
    });

  });

}));
