/**
 * Scubawhere API Documentation
 * This is the documentation for scubawhere's RMS API. This API is only to be used by authorized parties with valid auth tokens.  [Learn about scubawhere](http://www.scubawhere.com) to become an authorized consumer of our API 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: bryan@scubawhere.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ScubawhereApiDocumentation);
  }
}(this, function(expect, ScubawhereApiDocumentation) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ScubawhereApiDocumentation.Refund();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Refund', function() {
    it('should create an instance of Refund', function() {
      // uncomment below and update the code to test Refund
      //var instane = new ScubawhereApiDocumentation.Refund();
      //expect(instance).to.be.a(ScubawhereApiDocumentation.Refund);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instane = new ScubawhereApiDocumentation.Refund();
      //expect(instance).to.be();
    });

    it('should have the property bookingId (base name: "booking_id")', function() {
      // uncomment below and update the code to test the property bookingId
      //var instane = new ScubawhereApiDocumentation.Refund();
      //expect(instance).to.be();
    });

    it('should have the property amount (base name: "amount")', function() {
      // uncomment below and update the code to test the property amount
      //var instane = new ScubawhereApiDocumentation.Refund();
      //expect(instance).to.be();
    });

    it('should have the property currencyId (base name: "currency_id")', function() {
      // uncomment below and update the code to test the property currencyId
      //var instane = new ScubawhereApiDocumentation.Refund();
      //expect(instance).to.be();
    });

    it('should have the property paymentGatewayId (base name: "payment_gateway_id")', function() {
      // uncomment below and update the code to test the property paymentGatewayId
      //var instane = new ScubawhereApiDocumentation.Refund();
      //expect(instance).to.be();
    });

    it('should have the property receivedAt (base name: "received_at")', function() {
      // uncomment below and update the code to test the property receivedAt
      //var instane = new ScubawhereApiDocumentation.Refund();
      //expect(instance).to.be();
    });

    it('should have the property paymentGateway (base name: "payment_gateway")', function() {
      // uncomment below and update the code to test the property paymentGateway
      //var instane = new ScubawhereApiDocumentation.Refund();
      //expect(instance).to.be();
    });

    it('should have the property currency (base name: "currency")', function() {
      // uncomment below and update the code to test the property currency
      //var instane = new ScubawhereApiDocumentation.Refund();
      //expect(instance).to.be();
    });

  });

}));
